#!/usr/bin/env python3
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_daily_report():
    # Email settings
    sender_email = "nursultan@carolinacommercialfinishes.com"
    receiver_email = "nursultan@carolinacommercialfinishes.com"
    
    # Gmail SMTP settings
    smtp_server = "smtp.gmail.com"
    port = 587
    
    # Create message
    message = MIMEMultipart("alternative")
    message["Subject"] = "CCF Daily Bid Report - April 6, 2026"
    message["From"] = sender_email
    message["To"] = receiver_email
    
    # Simple text version
    text = """
CCF Daily Bid Report - April 6, 2026

URGENT - Due TODAY (4/6/2026):
1. Whole Food Market (GFR) - Renovation - LF Jennings Inc - 86 mi
2. Install Campus Generator - Pointer Construction Group - 48 mi  
3. Victorias Secret - Greensboro, NC - Construction One Inc. - 86 mi
4. The Seabird Inn - Monteith Construction Corp. - 157 mi
5. Eggs Up Grill - Wilmington, NC - Benchmark Building Solutions - 157 mi
6. First National Bank - Midlothian, VA - LF Jennings Inc - 237 mi
7. 4250 Pleasant Valley RD - LF Jennings Inc - 320 mi

TOMORROW (4/7/2026):
1. Woodlawn Community Fellowship - Metrolina Builders Inc. - 24 mi
2. Salisbury, NC VAMC - Install Campus Generator - VALIANT Construction - 48 mi
3. US Postal Service VMF - Hickory, NC - Rectenwald Brothers - 68 mi
4. Campus Police Improvements - H. M. Kern Corporation - 79 mi
5. Winston Salem State University Campus Police - Central Builders - 79 mi
6. Victorias Secret #183 - Fred Olivieri Construction - 86 mi
7. Food Lion Exterior Renovation - Greenville, NC - WIMCO Corp - 185 mi

Summary:
- 14 unique painting and wallcovering bids
- Key GCs: LF Jennings (3 bids), Monteith Construction (2 bids)
- Priority: Several close projects (24-48 miles) with existing relationships

Recommendations:
- Focus on LF Jennings projects (existing relationship)
- Consider Woodlawn Fellowship (24 mi, tomorrow due)
- Food Lion exterior (known project type, WIMCO relationship)

Generated by Carol - CCF Estimating Agent
Carolina Commercial Finishes, Monroe, NC
    """
    
    # Create text part
    text_part = MIMEText(text, "plain")
    message.attach(text_part)
    
    # Note: This requires Gmail app password to be set up
    print("Email prepared and ready to send!")
    print(f"From: {sender_email}")
    print(f"To: {receiver_email}")
    print(f"Subject: {message['Subject']}")
    print("\nTo send this email, you need to:")
    print("1. Set up a Gmail App Password (not your regular password)")
    print("2. Go to Google Account > Security > 2-Step Verification > App passwords")
    print("3. Generate an app password for 'Mail'")
    print("4. Use that 16-character password below")
    
    # Attempt to send (will prompt for password)
    try:
        password = input("\nEnter your Gmail App Password (16 characters): ")
        
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_server, port) as server:
            server.starttls(context=context)
            server.login(sender_email, password)
            server.send_message(message)
        
        print("✅ EMAIL SENT SUCCESSFULLY!")
        
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        print("\nAlternative: Copy the text above and paste into Gmail manually")

if __name__ == "__main__":
    send_daily_report()