#!/usr/bin/env python3
"""Send daily bid report via Gmail"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def send_daily_report():
    # Email settings
    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    sender_email = "nursultan@carolinacommericalfinishes.com"  # CCF business email
    receiver_email = "nursultan@carolinacommericalfinishes.com"  # Send to yourself
    
    # You'll need an app password from Google for this to work
    # For now, we'll create the draft via Gmail API instead
    
    subject = f"CCF Daily Bid Report - {datetime.now().strftime('%B %d, %Y')}"
    
    # Read the HTML content
    with open("daily_report_email.html", "r", encoding="utf-8") as f:
        html_content = f.read()
    
    # Create plain text version
    text_content = f"""
CCF Daily Bid Report - April 6, 2026

🚨 URGENT - Due TODAY (4/6/2026):
1. Whole Food Market (GFR) - Renovation (CC) - 86 mi - LF Jennings Inc
2. Install Campus Generator (BC) - 48 mi - Pointer Construction Group
3. Victorias Secret - Greensboro, NC (BC) - 86 mi - Construction One Inc.
4. The Seabird Inn (CC) - 157 mi - Monteith Construction Corp.
5. Eggs Up Grill - Wilmington, NC (BC) - 157 mi - Benchmark Building Solutions
6. First National Bank - Midlothian, VA (CC) - 237 mi - LF Jennings Inc
7. 4250 Pleasant Valley RD (CC) - 320 mi - LF Jennings Inc

📅 TOMORROW (4/7/2026):
1. Woodlawn Community Fellowship (BC) - 24 mi - Metrolina Builders Inc.
2. Salisbury, NC VAMC - Install Campus Generator (BC) - 48 mi - VALIANT Construction
3. US Postal Service VMF - Hickory, NC (BC) - 68 mi - Rectenwald Brothers
4. Campus Police Improvements (CC) - 79 mi - H. M. Kern Corporation
5. Winston Salem State University Campus Police (CC) - 79 mi - Central Builders
6. Victorias Secret #183 (BC) - 86 mi - Fred Olivieri Construction
7. Food Lion Exterior Renovation - Greenville, NC (CC) - 185 mi - WIMCO Corp

📊 Summary:
- 14 unique painting & wallcovering bids
- Types: 4 Retail, 3 Government/VA, 2 Banking, 2 Restaurant, 1 Religious, 1 Education, 1 Hospitality
- Key GCs: LF Jennings (3 bids), Monteith Construction (2 bids)
- Priority: Several close projects (24-48 miles) with existing relationships

🎯 Recommendations:
- Focus on LF Jennings projects (existing relationship)
- Consider Woodlawn Fellowship (24 mi, tomorrow due)
- Food Lion exterior (known project type, WIMCO relationship)

Generated by Carol - CCF Estimating Agent
Carolina Commercial Finishes, Monroe, NC
"""

    print("Email content prepared:")
    print(f"Subject: {subject}")
    print(f"HTML length: {len(html_content)} characters")
    print(f"Text length: {len(text_content)} characters")
    print("\nTo send via Gmail, you would need to:")
    print("1. Set up Gmail API credentials or app password")
    print("2. Configure SMTP authentication")
    print("3. Or use the Gmail MCP tools if available")
    
    return subject, html_content, text_content

if __name__ == "__main__":
    send_daily_report()