import smtplib
from email.mime.text import MIMEText
import getpass

# Email configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
FROM_EMAIL = "nursultan@carolinacommercialfinishes.com"
TO_EMAIL = "nursultan@carolinacommercialfinishes.com"

# Email content
SUBJECT = "CCF Daily Bid Report - April 6, 2026"
BODY = """CCF Daily Bid Report - April 6, 2026

URGENT - Due TODAY (4/6/2026):
1. Whole Food Market (GFR) - Renovation - LF Jennings Inc - 86 mi
2. Install Campus Generator - Pointer Construction Group - 48 mi  
3. Victoria's Secret - Greensboro, NC - Construction One Inc. - 86 mi
4. The Seabird Inn - Monteith Construction Corp. - 157 mi
5. Eggs Up Grill - Wilmington, NC - Benchmark Building Solutions - 157 mi
6. First National Bank - Midlothian, VA - LF Jennings Inc - 237 mi
7. 4250 Pleasant Valley RD - LF Jennings Inc - 320 mi

TOMORROW (4/7/2026):
1. Woodlawn Community Fellowship - Metrolina Builders Inc. - 24 mi
2. Salisbury, NC VAMC - Install Campus Generator - VALIANT Construction - 48 mi
3. US Postal Service VMF - Hickory, NC - Rectenwald Brothers - 68 mi
4. Campus Police Improvements - H. M. Kern Corporation - 79 mi
5. Winston Salem State University Campus Police - Central Builders - 79 mi
6. Victoria's Secret #183 - Fred Olivieri Construction - 86 mi
7. Food Lion Exterior Renovation - Greenville, NC - WIMCO Corp - 185 mi

Summary:
- 14 unique painting and wallcovering bids
- Key GCs: LF Jennings (3 bids), Monteith Construction (2 bids)
- Priority: Several close projects (24-48 miles) with existing relationships

Recommendations:
- Focus on LF Jennings projects (existing relationship)
- Consider Woodlawn Fellowship (24 mi, tomorrow due)
- Food Lion exterior (known project type, WIMCO relationship)

Generated by Carol - CCF Estimating Agent
Carolina Commercial Finishes, Monroe, NC"""

def send_email():
    try:
        # Create message
        msg = MIMEText(BODY)
        msg['Subject'] = SUBJECT
        msg['From'] = FROM_EMAIL
        msg['To'] = TO_EMAIL
        
        # Connect and send
        print("Connecting to Gmail SMTP...")
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        
        # This will need your Gmail app password
        password = getpass.getpass("Enter Gmail app password: ")
        server.login(FROM_EMAIL, password)
        
        # Send the email
        server.send_message(msg)
        server.quit()
        
        print("✓ EMAIL SENT SUCCESSFULLY!")
        return True
        
    except Exception as e:
        print(f"✗ Error: {e}")
        print("\nIf you don't have a Gmail app password:")
        print("1. Go to Google Account settings")
        print("2. Security > 2-Step Verification > App passwords")
        print("3. Generate password for 'Mail'")
        return False

if __name__ == "__main__":
    send_email()